<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @see \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer
 */
/** @var $block \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php $_item = $block->getItem() ?>
<?php $items = array_merge([$_item], $_item->getChildrenItems()); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>
<?php
/** @var \Magento\Catalog\Helper\Data $catalogHelper */
$catalogHelper = $block->getData('catalogHelper');
?>
<?php $jsonHelper = $block->helper('Magento\Framework\Json\Helper\Data');?>

<?php $_prevOptionId = '' ?>

<?php if ($block->getOrderOptions() || $_item->getDescription() || $block->canDisplayGiftmessage()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item): ?>
    <?php $block->setPriceDataObject($_item) ?>
    <?php $attributes = $block->getSelectionAttributes($_item) ?>
    <?php if ($_item->getParentItem()): ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
        <tr>
            <td class="col-product">
                <div class="option-label"><?= $block->escapeHtml($attributes['option_label']) ?></div>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="last">&nbsp;</td>
        </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr<?= (++$_index==$_count && !$_showlastRow)?' class="border"':'' ?>>
        <?php if (!$_item->getParentItem()): ?>
        <td class="col-product">
            <div class="product-title" id="order_item_<?= $block->escapeHtmlAttr($_item->getId()) ?>_title">
                <?= $block->escapeHtml($_item->getName()) ?>
            </div>
            <div class="product-sku-block">
                <span><?= $block->escapeHtml(__('SKU')) ?>:</span>
                <?= /* @noEscape */ implode('<br />', $catalogHelper->splitSku($_item->getSku())) ?>
            </div>
        </td>
        <?php else: ?>
        <td class="col-product">
            <div class="option-value"><?= $block->getValueHtml($_item) ?></div>
        </td>
        <?php endif; ?>
        <td class="col-status">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->escapeHtml($_item->getStatus()) ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-price-original">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @noEscape */ $block->displayPriceAttribute('original_price') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-price">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'price') ?>
            <?php else: ?>
                    &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-ordered-qty">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <table class="qty-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Ordered')) ?></th>
                        <td><?= (float)$_item->getQtyOrdered() * 1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getQtyInvoiced()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Invoiced')) ?></th>
                        <td><?= (float)$_item->getQtyInvoiced() * 1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyShipped() && $block->isShipmentSeparately($_item)): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Shipped')) ?></th>
                        <td><?= (float)$_item->getQtyShipped() * 1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyRefunded()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Refunded')) ?></th>
                        <td><?= (float)$_item->getQtyRefunded() * 1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyCanceled()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Canceled')) ?></th>
                        <td><?= (float)$_item->getQtyCanceled() * 1 ?></td>
                    </tr>
                    <?php endif; ?>
                </table>
            <?php elseif ($block->isShipmentSeparately($_item)): ?>
                <table class="qty-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Ordered')) ?></th>
                        <td><?= (float)$_item->getQtyOrdered() * 1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getQtyShipped()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Shipped')) ?></th>
                        <td><?= (float)$_item->getQtyShipped() * 1 ?></td>
                    </tr>
                    <?php endif; ?>
                </table>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-subtotal">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'subtotal') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-tax-amount">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @noEscape */ $block->displayPriceAttribute('tax_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-tax-percent">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @noEscape */ $block->displayTaxPercent($_item) ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-discont">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @noEscape */ $block->displayPriceAttribute('discount_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-total last">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'total') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
    </tr>
    <?php if ($_item->getDesigns()): ?>
        <?php $designs = $jsonHelper->jsonDecode($_item->getDesigns());?>
        <tr class="design-container">
            <td>
                <strong>Designs List</strong>
                <?php foreach ($designs as $design):?>
                    <div class="downloads-item">
                        <div class="item-icon">
                            <svg viewBox="0 0 512 512" height="16" width="16" class="icon"><path d="M156.2,199.7c7.5-7.5,15.9-13.8,24.8-18.7c49.6-27.3,113.1-12.8,145,35.5l-38.5,38.5c-11.1-25.2-38.5-39.6-65.8-33.5c-10.3,2.3-20.1,7.4-28,15.4l-73.9,73.9c-22.4,22.4-22.4,58.9,0,81.4c22.4,22.4,58.9,22.4,81.4,0l22.8-22.8c20.7,8.2,42.9,11.5,64.9,9.9l-50.3,50.3c-43.1,43.1-113,43.1-156.1,0c-43.1-43.1-43.1-113-0-156.1L156.2,199.7z M273.6,82.3l-50.3,50.3c21.9-1.6,44.2,1.6,64.9,9.9l22.8-22.8c22.4-22.4,58.9-22.4,81.4,0c22.4,22.4,22.4,58.9,0,81.4l-73.9,73.9c-22.5,22.5-59.1,22.3-81.4,0c-5.2-5.2-9.7-11.7-12.5-18l-38.5,38.5c4,6.1,8.3,11.5,13.7,16.9c13.9,13.9,31.7,24.3,52.1,29.3c26.5,6.4,54.8,2.8,79.2-10.6c8.9-4.9,17.3-11.1,24.8-18.7l73.9-73.9c43.1-43.1,43.1-113,0-156.1C386.6,39.2,316.7,39.2,273.6,82.3z"></path></svg>
                        </div>
                        <div class="item-link">
                            <a href="https://dashboard.printcart.com/design/<?php echo $design['id'];?>" rel="2" target="_blank" title="File Downloads">
                                <b><?php echo $design['id'];?></b>
                            </a>
                        </div>
                    </div>
                <?php endforeach;?>
            </td>
        </tr>
    <?php endif;?>
<?php endforeach; ?>
<?php if ($_showlastRow): ?>
    <tr<?php if (!$block->canDisplayGiftmessage()) { echo ' class="border"'; } ?>>
        <td class="col-product">
            <?php if ($block->getOrderOptions()): ?>
                <dl class="item-options">
                <?php foreach ($block->getOrderOptions() as $option): ?>
                    <dt><?= $block->escapeHtml($option['label']) ?>:</dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?= $block->escapeHtml($option['value']) ?>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->truncateString($option['value'], 55, '', $_remainder)) ?>
                        <?php if ($_remainder):?>
                            ... <span id="<?= $block->escapeHtmlAttr($_id = 'id' . uniqid())
                            ?>"><?= $block->escapeHtml($_remainder) ?></span>
                            <?php $escapedId = /* @noEscape */ $block->escapeJs($_id);
                            $scriptString = <<<script
                                require(['prototype'], function(){
                                    $('{$escapedId}').hide();
                                    $('{$escapedId}').up().observe('mouseover', function(){\$('{$escapedId}').show();});
                                    $('{$escapedId}').up().observe('mouseout',  function(){\$('{$escapedId}').hide();});
                                });
script;
                            ?>
                            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>
